//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: NodeEditor.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "NodeEditor.h"


// Declare the bitmap loading function
extern void wxCrafterY8Mp03InitBitmapResources();

static bool bBitmapLoaded = false;


NodeEditorMainframeBase::NodeEditorMainframeBase(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxMDIParentFrame(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxCrafterY8Mp03InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    m_menuBar = new wxMenuBar(0);
    this->SetMenuBar(m_menuBar);
    
    m_menuFile = new wxMenu();
    m_menuBar->Append(m_menuFile, _("File"));
    
    m_menuItem153 = new wxMenuItem(m_menuFile, wxID_NEW, _("New"), wxT(""), wxITEM_NORMAL);
    m_menuFile->Append(m_menuItem153);
    
    m_menuItemExit = new wxMenuItem(m_menuFile, wxID_ANY, _("Exit"), wxT(""), wxITEM_NORMAL);
    m_menuFile->Append(m_menuItemExit);
    
    SetName(wxT("NodeEditorMainframeBase"));
    SetSize(wxDLG_UNIT(this, wxSize(800,600)));
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
#if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
#endif
    // Connect events
    this->Connect(m_menuItem153->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(NodeEditorMainframeBase::onNew), NULL, this);
    this->Connect(m_menuItemExit->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(NodeEditorMainframeBase::onExit), NULL, this);
    
}

NodeEditorMainframeBase::~NodeEditorMainframeBase()
{
    this->Disconnect(m_menuItem153->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(NodeEditorMainframeBase::onNew), NULL, this);
    this->Disconnect(m_menuItemExit->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(NodeEditorMainframeBase::onExit), NULL, this);
    
}

NodeEditorPanelBase::NodeEditorPanelBase(wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style)
    : wxPanel(parent, id, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxCrafterY8Mp03InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    boxSizer67 = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizer67);
    
    m_splitter = new wxSplitterWindow(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxSP_3DBORDER|wxSP_3DSASH|wxSP_3D);
    m_splitter->SetSashGravity(0.5);
    m_splitter->SetMinimumPaneSize(10);
    
    boxSizer67->Add(m_splitter, 1, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    m_splitterLeft = new wxPanel(m_splitter, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_splitter, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    
    boxSizer85 = new wxBoxSizer(wxVERTICAL);
    m_splitterLeft->SetSizer(boxSizer85);
    
    m_nodeTypes = new wxTreeCtrl(m_splitterLeft, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_splitterLeft, wxSize(-1,-1)), wxTR_DEFAULT_STYLE);
    m_nodeTypes->SetToolTip(_("Node Type List"));
    
    boxSizer85->Add(m_nodeTypes, 1, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    wxArrayString m_listTraceArr;
    m_listTrace = new wxListBox(m_splitterLeft, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_splitterLeft, wxSize(-1,-1)), m_listTraceArr, wxLB_SINGLE);
    
    boxSizer85->Add(m_listTrace, 1, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    m_splitterRight = new wxPanel(m_splitter, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_splitter, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    m_splitter->SplitVertically(m_splitterLeft, m_splitterRight, 0);
    
    canvasSizer = new wxBoxSizer(wxVERTICAL);
    m_splitterRight->SetSizer(canvasSizer);
    
    m_toolbar173 = new wxToolBar(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTB_FLAT);
    m_toolbar173->SetToolBitmapSize(wxSize(16,16));
    
    boxSizer67->Add(m_toolbar173, 0, wxALL, WXC_FROM_DIP(5));
    
    m_toolbar173->AddTool(wxID_OPEN, _("Tool Label"), wxArtProvider::GetBitmap(wxART_FILE_OPEN, wxART_TOOLBAR, wxDefaultSize), wxNullBitmap, wxITEM_NORMAL, wxT(""), wxT(""), NULL);
    
    m_toolbar173->AddTool(wxID_SAVE, _("Tool Label"), wxArtProvider::GetBitmap(wxART_FILE_SAVE, wxART_TOOLBAR, wxDefaultSize), wxNullBitmap, wxITEM_NORMAL, wxT(""), wxT(""), NULL);
    
    m_toolbar173->AddTool(wxID_SAVEAS, _("Tool Label"), wxArtProvider::GetBitmap(wxART_FILE_SAVE_AS, wxART_TOOLBAR, wxDefaultSize), wxNullBitmap, wxITEM_NORMAL, wxT(""), wxT(""), NULL);
    
    m_toolbar173->AddTool(wxID_CLEAR, _("Tool Label"), wxArtProvider::GetBitmap(wxART_NEW, wxART_TOOLBAR, wxDefaultSize), wxNullBitmap, wxITEM_NORMAL, _("Clear"), wxT(""), NULL);
    m_toolbar173->Realize();
    
    SetName(wxT("NodeEditorPanelBase"));
    SetSize(wxDLG_UNIT(this, wxSize(800,600)));
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    // Connect events
    this->Connect(wxID_OPEN, wxEVT_COMMAND_TOOL_CLICKED, wxCommandEventHandler(NodeEditorPanelBase::onOpen), NULL, this);
    this->Connect(wxID_SAVE, wxEVT_COMMAND_TOOL_CLICKED, wxCommandEventHandler(NodeEditorPanelBase::onSave), NULL, this);
    this->Connect(wxID_SAVEAS, wxEVT_COMMAND_TOOL_CLICKED, wxCommandEventHandler(NodeEditorPanelBase::onSaveAs), NULL, this);
    this->Connect(wxID_CLEAR, wxEVT_COMMAND_TOOL_CLICKED, wxCommandEventHandler(NodeEditorPanelBase::onClear), NULL, this);
    
}

NodeEditorPanelBase::~NodeEditorPanelBase()
{
    this->Disconnect(wxID_OPEN, wxEVT_COMMAND_TOOL_CLICKED, wxCommandEventHandler(NodeEditorPanelBase::onOpen), NULL, this);
    this->Disconnect(wxID_SAVE, wxEVT_COMMAND_TOOL_CLICKED, wxCommandEventHandler(NodeEditorPanelBase::onSave), NULL, this);
    this->Disconnect(wxID_SAVEAS, wxEVT_COMMAND_TOOL_CLICKED, wxCommandEventHandler(NodeEditorPanelBase::onSaveAs), NULL, this);
    this->Disconnect(wxID_CLEAR, wxEVT_COMMAND_TOOL_CLICKED, wxCommandEventHandler(NodeEditorPanelBase::onClear), NULL, this);
    
}
